version: "3.8"

services:
  pgvector:
    image: ankane/pgvector
    ports:
      - "0.0.0.0:${DATABASE_PORT}:5432"
    volumes:
      - "$HOME/pgvector/data:/var/lib/postgresql/data"
      - "$APP_DIR/docker/postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
