# The builder image, used to build the virtual environment
FROM python:3.11-buster

RUN apt-get update && apt-get install -y git

RUN pip install poetry

#ENV POETRY_NO_INTERACTION=1 \
#    POETRY_VIRTUALENVS_IN_PROJECT=1 \
#    POETRY_VIRTUALENVS_CREATE=1 \

ENV POETRY_CACHE_DIR=/tmp/poetry_cache

# A directory to have app data 
WORKDIR /app

COPY . .

RUN poetry install --without dev && rm -rf $POETRY_CACHE_DIR

